version: "3"

services:
  padel_frontend:
    container_name: padel_frontend_container
    build:
      context: ./
      dockerfile: dockerfile-dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"